services:
  - type: web
    name: retail-management-backend
    runtime: node
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false